### ISSUE TITLE
是否可以提供8650编译好的apk

### ISSUE THREAD

**Issue by AndreaChiChengdu** [XiaoMi/StableDiffusionOnDevice#4]
你好，我是一名米粉，设备为小米14pro，慕名而来，想要体验下手机上的出图体验。不过并非专业开发者，对android开发和高通工具链不太了解也没有对应的开发环境。是否可以直接提供8650的apk到release？
感谢

**Comment by AndreaChiChengdu** [comment]
已经编译成功 关闭

**Comment by MarioZZJ** [comment]
您好，我编译出来的apk安装使用后遇到了模型加载失败的问题，请问您编译出来的apk有这样的问题吗？ @AndreaChiChengdu 

我的设备是小米14，系统版本os1.0.24.6.11.DEV，android 14

如果没有问题，请问您方便分享一下您的apk吗

**Comment by cute-omega** [comment]
很冒昧打扰您，请问能提供一下8550的apk吗？我不知道如何打包成apk。我的设备是小米13pro，系统1.0.9UMBEUXM，安卓14
